Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: src/handlers/put-item.putItemHandler
      CodeUri: /Users/sjanyavula/Projects/GdriveImagetoPDF
      Runtime: nodejs14.x